pipelines:
  default:
    - parallel:
        - step:
            image: elixir:latest
            name: Latest Elixir
            script:
            - mix local.hex --force
            - mix local.rebar --force
            - mix deps.get
            - mix test
        - step:
            image: elixir:1.6-alpine
            name: Elixir 1.6
            script:
            - apk add --no-cache openssl openssh-client
            - mix local.hex --force
            - mix local.rebar --force
            - mix deps.get
            - mix test
        - step:
            image: elixir:1.5-alpine
            name: Elixir 1.5
            script:
            - apk add --no-cache openssl openssh-client
            - mix local.hex --force
            - mix local.rebar --force
            - mix deps.get
            - mix test
        - step:
            image: elixir:1.4-slim
            name: Elixir 1.4
            script:
            - apt update && apt install openssl openssh-client
            - mix local.hex --force
            - mix local.rebar --force
            - mix deps.get
            - mix test
